version: 1.0.{build}
image: Ubuntu2004
environment:
  nodejs_version: "18"

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - nvm install $nodejs_version
  - npm install
  - npm install webpack webpack-cli gh-pages --save-dev

build_script:
  - npm run build
  - ls -R dist  # Проверка содержимого папки dist

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"